import {
  siAstro,
  siC,
  siClojure,
  siCmake,
  siCoffeescript,
  siCplusplus,
  siCrystal,
  siCss,
  siDart,
  siDocker,
  siElixir,
  siErlang,
  siFsharp,
  siGnubash,
  siGnuemacs,
  siGo,
  siHaskell,
  siHtml5,
  siJavascript,
  siJulia,
  siJupyter,
  siKotlin,
  siLatex,
  siLess,
  siLua,
  siMarkdown,
  siNim,
  siNixos,
  siOcaml,
  siOpenjdk,
  siPerl,
  siPhp,
  siPython,
  siR,
  siRacket,
  siRuby,
  siRust,
  siSass,
  siScala,
  siSolidity,
  siSvelte,
  siSwift,
  siTypescript,
  siVim,
  siVuedotjs,
  siZig,
} from "simple-icons";

export interface LangIcon {
  path: string | null;
  hex: string;
}

const ICONS: Record<string, { path: string; hex: string }> = {
  "JavaScript": siJavascript,
  "TypeScript": siTypescript,
  "Python": siPython,
  "Go": siGo,
  "Rust": siRust,
  "Java": siOpenjdk,
  "C++": siCplusplus,
  "C": siC,
  "PHP": siPhp,
  "Ruby": siRuby,
  "Swift": siSwift,
  "Kotlin": siKotlin,
  "Shell": siGnubash,
  "HTML": siHtml5,
  "CSS": siCss,
  "SCSS": siSass,
  "Sass": siSass,
  "Less": siLess,
  "Vue": siVuedotjs,
  "Svelte": siSvelte,
  "Astro": siAstro,
  "Dart": siDart,
  "Scala": siScala,
  "Haskell": siHaskell,
  "Lua": siLua,
  "R": siR,
  "Julia": siJulia,
  "Elixir": siElixir,
  "Erlang": siErlang,
  "Clojure": siClojure,
  "Perl": siPerl,
  "Zig": siZig,
  "Nim": siNim,
  "OCaml": siOcaml,
  "F#": siFsharp,
  "Crystal": siCrystal,
  "Racket": siRacket,
  "CoffeeScript": siCoffeescript,
  "Solidity": siSolidity,
  "Markdown": siMarkdown,
  "Jupyter Notebook": siJupyter,
  "Dockerfile": siDocker,
  "CMake": siCmake,
  "Nix": siNixos,
  "Emacs Lisp": siGnuemacs,
  "Vim Script": siVim,
  "Vim Snippet": siVim,
  "TeX": siLatex,
};

const COLORS: Record<string, string> = {
  "C#": "178600",
  "PowerShell": "012456",
  "Objective-C": "438EFF",
  "Objective-C++": "6866FB",
  "MATLAB": "E16737",
  "Groovy": "4298B8",
  "Assembly": "6E4C13",
  "Makefile": "427819",
  "Batchfile": "C1F12E",
  "Roff": "ECDEBE",
  "Verilog": "B2B7F8",
  "VHDL": "ADB2CB",
  "Fortran": "4D41B1",
  "COBOL": "005CA5",
  "Pascal": "E3F171",
  "Visual Basic .NET": "945DB7",
  "Blade": "F7523F",
  "Handlebars": "F7931E",
  "EJS": "A91E50",
  "Twig": "C1D026",
  "Smarty": "F0C040",
  "Mustache": "724B3B",
  "Jinja": "A52A22",
  "Starlark": "76D275",
  "HCL": "844FBA",
  "Smalltalk": "596706",
  "Common Lisp": "3FB68B",
  "Scheme": "1E4AEC",
  "Prolog": "74283C",
  "Ada": "02F88C",
  "D": "BA595E",
  "V": "4F87C4",
  "Odin": "60AFFE",
  "Mojo": "FF4C1F",
  "Zeek": "F5C800",
  "SQL": "E38C00",
  "PLpgSQL": "336790",
  "TSQL": "E38C00",
  "Rich Text Format": "A0A0A0",
  "Jsonnet": "0064BD",
  "Cuda": "3A4E3A",
  "Metal": "8F14E9",
  "GLSL": "5686A5",
  "HLSL": "AACE60",
  "QML": "44A51C",
  "Svelte": "FF3E00",
  "Solidity": "AA6746",
};

export function languageIcon(name: string | null): LangIcon | null {
  if (!name) {
    return null;
  }
  const icon = ICONS[name];
  if (icon) {
    return { path: icon.path, hex: `#${icon.hex}` };
  }
  const color = COLORS[name];
  return { path: null, hex: color ? `#${color}` : "#8b949e" };
}
